site_name: Visonic PmaxService Documentation
theme:
  name: material

nav:
- Home: 'index.md'
- Sending A Request: 'sending-a-request.md'
- Methods:
    - 'PmaxService/getApiVersion': 'methods/pmaxservice-getapiversion.md'
    - 'PmaxService/getBatteryLevel': 'methods/pmaxservice-getbatterylevel.md'
    - 'PmaxService/getConnectionType': 'methods/pmaxservice-getconnectiontype.md'
    - 'PmaxService/setPanelState': 'methods/pmaxservice-setpanelstate.md'
    - 'PmaxService/getDate': 'methods/pmaxservice-getdate.md'
    - 'PmaxService/getDateTime': 'methods/pmaxservice-getdatetime.md'
    - 'PmaxService/enableSsh': 'methods/pmaxservice-enablessh.md'
    - 'PmaxService/getLocationsList': 'methods/pmaxservice-getlocationslist.md'
    - 'PmaxService/getPanelStatuses': 'methods/pmaxservice-getpanelstatuses.md'
    - 'PmaxService/getPanelState': 'methods/pmaxservice-getpanelstate.md'
    - 'PmaxService/getDevicesConfig': 'methods/pmaxservice-getdevicesconfig.md'
    - 'PmaxService/isPanelConnected': 'methods/pmaxservice-ispanelconnected.md'
    - 'PmaxService/getUserCodes': 'methods/pmaxservice-getusercodes.md'