site_name: Visonic PmaxService Documentation
theme:
  name: material

nav:
- Home: 'index.md'
- Sending A Request: 'sending-a-request.md'
- Visonic API:
    - Introduction: 'visonic-api/introduction.md'
    - '/version': 'visonic-api/version.md'
- Methods:
    - 'PmaxService/getApiVersion': 'methods/pmaxservice-getapiversion.md'
    - 'PmaxService/getBatteryLevel': 'methods/pmaxservice-getbatterylevel.md'
    - 'PmaxService/getConnectionType': 'methods/pmaxservice-getconnectiontype.md'
    - 'PmaxService/setPanelState': 'methods/pmaxservice-setpanelstate.md'
    - 'PmaxService/getDate': 'methods/pmaxservice-getdate.md'
    - 'PmaxService/getDateTime': 'methods/pmaxservice-getdatetime.md'
    - 'PmaxService/enableSsh': 'methods/pmaxservice-enablessh.md'
    - 'PmaxService/getLocationsList': 'methods/pmaxservice-getlocationslist.md'
    - 'PmaxService/getPanelConfig': 'methods/pmaxservice-getpanelconfig.md'
    - 'PmaxService/getPanelStatuses': 'methods/pmaxservice-getpanelstatuses.md'
    - 'PmaxService/getPanelState': 'methods/pmaxservice-getpanelstate.md'
    - 'PmaxService/getDevicesConfig': 'methods/pmaxservice-getdevicesconfig.md'
    - 'PmaxService/getDeviceConfig': 'methods/pmaxservice-getdeviceconfig.md'
    - 'PmaxService/isPanelConnected': 'methods/pmaxservice-ispanelconnected.md'
    - 'PmaxService/getUserCodes': 'methods/pmaxservice-getusercodes.md'
    - 'PmaxService/getUserCode': 'methods/pmaxservice-getusercode.md'
    - 'PmaxService/getDeviceStatuses': 'methods/pmaxservice-getdevicestatuses.md'
    - 'PmaxService/getEepromVersion': 'methods/pmaxservice-geteepromversion.md'
    - 'PmaxService/getMaxDevices': 'methods/pmaxservice-getmaxdevices.md'
    - 'PmaxService/getMaxDevice': 'methods/pmaxservice-getmaxdevice.md'
    - 'PmaxService/getLocation': 'methods/pmaxservice-getlocation.md'
    - 'PmaxService/setDebugMode': 'methods/pmaxservice-setdebugmode.md'
