site_name: Visonic PmaxService Documentation
theme:
  name: material

nav:
- Home: 'index.md'
- Sending A Request: 'sending-a-request.md'
- Visonic API:
    - 'Introduction': 'visonic-api/introduction.md'
    - 'App IDs': 'visonic-api/app-ids.md'
    - '/version': 'visonic-api/version.md'
    - '/apptype': 'visonic-api/apptype.md'
    - '/rest_api':
      - '/installer':
        - '/8.0':
          - '/auth': 'visonic-api/rest/installer/8.0/auth.md'
          - '/panels': 'visonic-api/rest/installer/8.0/panels.md'
          - '/panel_info': 'visonic-api/rest/installer/8.0/panel-info.md'
          - '/customer_info': 'visonic-api/rest/installer/8.0/customer-info.md'
          - '/status': 'visonic-api/rest/installer/8.0/status.md'
          - '/configuration_list': 'visonic-api/rest/installer/8.0/configuration-list.md'
          - '/feature_set': 'visonic-api/rest/installer/8.0/feature-set.md'
          - '/events': 'visonic-api/rest/installer/8.0/events.md'
          - '/had':
            - '/rules':
              - '/event-profiles': 'visonic-api/rest/installer/8.0/had/rules/event-profiles.md'
          - '/panel':
            - '/diagnostics': 'visonic-api/rest/installer/8.0/panel/diagnostics.md'
            - '/login': 'visonic-api/rest/installer/8.0/panel/login.md'
      - '/10.0':
        - '/auth': 'visonic-api/rest/10.0/auth.md'
        - '/panels': 'visonic-api/rest/10.0/panels.md'
        - '/panel_access_info': 'visonic-api/rest/10.0/panel-access-info.md'
        - '/panel_info': 'visonic-api/rest/10.0/panel-info.md'
        - '/locations': 'visonic-api/rest/10.0/locations.md'
        - '/status': 'visonic-api/rest/10.0/status.md'
        - '/feature_set': 'visonic-api/rest/10.0/feature-set.md'
        - '/events': 'visonic-api/rest/10.0/events.md'
        - '/home_automation_devices': 'visonic-api/rest/10.0/home-automation-devices.md'
        - '/devices': 'visonic-api/rest/10.0/devices.md'
        - '/smart_devices': 'visonic-api/rest/10.0/smart-devices.md'
        - '/users': 'visonic-api/rest/10.0/users.md'
        - '/allow_switch_to_programming_mode': 'visonic-api/rest/10.0/allow-switch-to-programming-mode.md'
        - '/had':
          - '/rules':
            - 'event-profiles': 'visonic-api/rest/10.0/had/rules/event-profiles.md'
            - 'restrictions': 'visonic-api/rest/10.0/had/rules/restrictions.md'
      - '/panel':
        - '/login': 'visonic-api/rest/panel/login.md'
- Methods:
    - 'PmaxService/getApiVersion': 'methods/pmaxservice-getapiversion.md'
    - 'PmaxService/getBatteryLevel': 'methods/pmaxservice-getbatterylevel.md'
    - 'PmaxService/getConnectionType': 'methods/pmaxservice-getconnectiontype.md'
    - 'PmaxService/setPanelState': 'methods/pmaxservice-setpanelstate.md'
    - 'PmaxService/getDate': 'methods/pmaxservice-getdate.md'
    - 'PmaxService/getDateTime': 'methods/pmaxservice-getdatetime.md'
    - 'PmaxService/enableSsh': 'methods/pmaxservice-enablessh.md'
    - 'PmaxService/getLocationsList': 'methods/pmaxservice-getlocationslist.md'
    - 'PmaxService/getPanelConfig': 'methods/pmaxservice-getpanelconfig.md'
    - 'PmaxService/getPanelStatuses': 'methods/pmaxservice-getpanelstatuses.md'
    - 'PmaxService/getPanelState': 'methods/pmaxservice-getpanelstate.md'
    - 'PmaxService/getDevicesConfig': 'methods/pmaxservice-getdevicesconfig.md'
    - 'PmaxService/getDeviceConfig': 'methods/pmaxservice-getdeviceconfig.md'
    - 'PmaxService/isPanelConnected': 'methods/pmaxservice-ispanelconnected.md'
    - 'PmaxService/getUserCodes': 'methods/pmaxservice-getusercodes.md'
    - 'PmaxService/getUserCode': 'methods/pmaxservice-getusercode.md'
    - 'PmaxService/getDeviceStatuses': 'methods/pmaxservice-getdevicestatuses.md'
    - 'PmaxService/getEepromVersion': 'methods/pmaxservice-geteepromversion.md'
    - 'PmaxService/getMaxDevices': 'methods/pmaxservice-getmaxdevices.md'
    - 'PmaxService/getMaxDevice': 'methods/pmaxservice-getmaxdevice.md'
    - 'PmaxService/getLocation': 'methods/pmaxservice-getlocation.md'
    - 'PmaxService/setDebugMode': 'methods/pmaxservice-setdebugmode.md'
